version: '3'

services:
  postgres:
    image: postgres:16.1
    restart: always
    container_name: web4-spring-postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=web4-spring

  admin:
    image: adminer
    restart: always
    container_name: web4-spring-admin
    depends_on:
      - postgres
    ports:
      - 8084:8080